
import os

file_path = 'src/components/AdminPanel.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

start_marker = "{/* --- TAB 2: BRANDING & IDENTITY COLOR CONFIG --- */}"
end_marker = "{/* --- TAB: FACTORY MANAGEMENT --- */}"

start_idx = -1
for i, line in enumerate(lines):
    if start_marker in line:
        start_idx = i
        break

end_idx = -1
for i, line in enumerate(lines):
    if end_marker in line:
        end_idx = i
        break

if start_idx != -1 and end_idx != -1:
    content = [
        "      {/* --- TAB 2: BRANDING & IDENTITY COLOR CONFIG --- */}\n",
        "      {activeSubTab === 'branding' && (\n",
        "        <div className=\"bg-white rounded-[2rem] border border-gray-100 shadow-md p-6 sm:p-8 space-y-6\">\n",
        "          <div className=\"flex items-center gap-3 border-b border-gray-100 pb-4 mb-2\">\n",
        "            <Palette className={activeText} size={20} />\n",
        "            <div>\n",
        "              <h3 className=\"text-sm sm:text-base font-black text-slate-900\">تنظیمات تم رنگی و سفارشی‌سازی برندینگ</h3>\n",
        "              <p className=\"text-[10px] text-gray-400 font-bold\">رنگ‌های شاخص کل سایت، دکمه‌ها و نشان‌واره را از این بخش مدیریت کنید.</p>\n",
        "            </div>\n",
        "          </div>\n",
        "\n",
        "          <form onSubmit={handleBrandingSubmit} className=\"space-y-8\">\n",
        "            <div className=\"space-y-4\">\n",
        "              <label className=\"text-xs font-black text-slate-700 block\">انتخاب رنگ اصلی پرتال تجاری (Primary Theme Accent Color):</label>\n",
        "              \n",
        "              <div className=\"grid grid-cols-2 sm:grid-cols-5 gap-3\">\n",
        "                <button\n",
        "                  type=\"button\"\n",
        "                  onClick={() => setSelectedColor(\"emerald\")}\n",
        "                  className={`p-4 rounded-2xl border text-right transition-all cursor-pointer flex flex-col justify-between h-24 ${\n",
        "                    selectedColor === 'emerald' ? \"border-emerald-600 bg-emerald-50/40\" : \"border-slate-100 hover:bg-slate-50\"\n",
        "                  }`}\n",
        "                >\n",
        "                  <span className=\"w-5 h-5 bg-emerald-600 rounded-full block shadow-md\" />\n",
        "                  <div>\n",
        "                    <span className=\"block text-xs font-black text-slate-900\">سبز زمردی</span>\n",
        "                    <span className=\"text-[9px] text-slate-400 font-bold mt-0.5 block\">سبز سودآور سنتی</span>\n",
        "                  </div>\n",
        "                </button>\n",
        "\n",
        "                <button\n",
        "                  type=\"button\"\n",
        "                  onClick={() => setSelectedColor(\"indigo\")}\n",
        "                  className={`p-4 rounded-2xl border text-right transition-all cursor-pointer flex flex-col justify-between h-24 ${\n",
        "                    selectedColor === 'indigo' ? \"border-indigo-600 bg-indigo-50/40\" : \"border-slate-100 hover:bg-slate-50\"\n",
        "                  }`}\n",
        "                >\n",
        "                  <span className=\"w-5 h-5 bg-indigo-600 rounded-full block shadow-md\" />\n",
        "                  <div>\n",
        "                    <span className=\"block text-xs font-black text-slate-900\">نیلی مدرن</span>\n",
        "                    <span className=\"text-[9px] text-slate-400 font-bold mt-0.5 block\">رنگ استارتاپ‌های پیشرو</span>\n",
        "                  </div>\n",
        "                </button>\n",
        "\n",
        "                <button\n",
        "                  type=\"button\"\n",
        "                  onClick={() => setSelectedColor(\"amber\")}\n",
        "                  className={`p-4 rounded-2xl border text-right transition-all cursor-pointer flex flex-col justify-between h-24 ${\n",
        "                    selectedColor === 'amber' ? \"border-amber-600 bg-amber-50/40\" : \"border-slate-100 hover:bg-slate-50\"\n",
        "                  }`}\n",
        "                >\n",
        "                  <span className=\"w-5 h-5 bg-amber-600 rounded-full block shadow-md\" />\n",
        "                  <div>\n",
        "                    <span className=\"block text-xs font-black text-slate-900\">طلایی کهربایی</span>\n",
        "                    <span className=\"text-[9px] text-slate-400 font-bold mt-0.5 block\">رنگ طلا و بورس سنتی کالا</span>\n",
        "                  </div>\n",
        "                </button>\n",
        "\n",
        "                <button\n",
        "                  type=\"button\"\n",
        "                  onClick={() => setSelectedColor(\"sky\")}\n",
        "                  className={`p-4 rounded-2xl border text-right transition-all cursor-pointer flex flex-col justify-between h-24 ${\n",
        "                    selectedColor === 'sky' ? \"border-sky-600 bg-sky-50/40\" : \"border-slate-100 hover:bg-slate-50\"\n",
        "                  }`}\n",
        "                >\n",
        "                  <span className=\"w-5 h-5 bg-sky-600 rounded-full block shadow-md\" />\n",
        "                  <div>\n",
        "                    <span className=\"block text-xs font-black text-slate-900\">آبی آسمانی</span>\n",
        "                    <span className=\"text-[9px] text-slate-400 font-bold mt-0.5 block\">رنگ اعتماد و شفافیت</span>\n",
        "                  </div>\n",
        "                </button>\n",
        "              </div>\n",
        "            </div>\n",
        "\n",
        "            <div className=\"bg-slate-50/60 p-5 rounded-[1.5rem] border border-slate-100/80 space-y-4\">\n",
        "              <h4 className=\"text-xs font-black text-slate-800 flex items-center gap-1.5\">\n",
        "                ✏️ شخصی‌سازی عناوین و هویت بصری پلتفرم\n",
        "              </h4>\n",
        "              <p className=\"text-[10px] text-slate-400 font-bold leading-relaxed\">\n",
        "                این فیلدها مستقیما در سربرگ، کاتالوگ‌های دانلود، فاکتورها و پنل کاربری خریداران قرار می‌گیرند.\n",
        "              </p>\n",
        "              <div className=\"grid grid-cols-1 sm:grid-cols-2 gap-6 pt-2\">\n",
        "                <div className=\"space-y-1.5\">\n",
        "                  <label className=\"text-[11px] font-black text-slate-500 block\">نام اختصاصی پلتفرم (مثلا: بازرگانی علی):</label>\n",
        "                  <input\n",
        "                    type=\"text\"\n",
        "                    value={customAppName}\n",
        "                    onChange={(e) => setCustomAppName(e.target.value)}\n",
        "                    className=\"w-full px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-xs font-black text-slate-800 text-right\"\n",
        "                  />\n",
        "                </div>\n",
        "                <div className=\"space-y-1.5\">\n",
        "                  <label className=\"text-[11px] font-black text-slate-500 block\">شعار فرعی سامانه:</label>\n",
        "                  <input\n",
        "                    type=\"text\"\n",
        "                    value={customAppSub}\n",
        "                    onChange={(e) => setCustomAppSub(e.target.value)}\n",
        "                    className=\"w-full px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-800 text-right\"\n",
        "                  />\n",
        "                </div>\n",
        "                <div className=\"space-y-1.5 sm:col-span-2\">\n",
        "                  <label className=\"text-[11px] font-black text-slate-500 block\">لینک مستقیم کاتالوگ PDF رسمی (جهت دانلود کاربران):</label>\n",
        "                  <input\n",
        "                    type=\"text\"\n",
        "                    value={catalogPdfUrl}\n",
        "                    onChange={(e) => setCatalogPdfUrl(e.target.value)}\n",
        "                    placeholder=\"https://example.com/catalog.pdf\"\n",
        "                    className=\"w-full px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-xs font-mono text-left\"\n",
        "                    dir=\"ltr\"\n",
        "                  />\n",
        "                </div>\n",
        "\n",
        "                <div className=\"space-y-1.5 sm:col-span-2 border-t border-slate-100 pt-4\">\n",
        "                  <label className=\"text-[11px] font-black text-slate-500 block\">لینک تصویر لوگوی اصلی پلتفرم:</label>\n",
        "                  <input\n",
        "                    type=\"text\"\n",
        "                    value={customLogoUrl}\n",
        "                    onChange={(e) => setCustomLogoUrl(e.target.value)}\n",
        "                    placeholder=\"https://raw.githubusercontent.com/antigravity-agent/media/main/dastavval_logo.png\"\n",
        "                    className=\"w-full px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-xs font-mono text-left\"\n",
        "                    dir=\"ltr\"\n",
        "                  />\n",
        "                </div>\n",
        "              </div>\n",
        "            </div>\n",
        "\n",
        "            <div className=\"bg-slate-50/60 p-5 rounded-[1.5rem] border border-slate-100/80 space-y-4\">\n",
        "              <h4 className=\"text-xs font-black text-slate-800 flex items-center gap-1.5\">\n",
        "                📥 سیستم واردکننده دسته‌ای کالاها با کدهای JSON\n",
        "              </h4>\n",
        "              <p className=\"text-[10px] text-slate-400 font-bold leading-relaxed\">\n",
        "                آرایه یا آبجکت معتبری از کدهای کالاها را در کارتن وارد کنید تا بصورت لحظه‌ای در خط تولید ثبت شوند.\n",
        "              </p>\n",
        "              <textarea\n",
        "                value={jsonImportText}\n",
        "                onChange={(e) => setJsonImportText(e.target.value)}\n",
        "                className=\"w-full h-28 p-3 bg-white border border-slate-200 rounded-xl text-xs font-mono text-left\"\n",
        "                dir=\"ltr\"\n",
        "              />\n",
        "              <button\n",
        "                type=\"button\"\n",
        "                onClick={handleJsonGoodsImport}\n",
        "                className=\"px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white font-black text-[10px] rounded-lg cursor-pointer transition-all hover:scale-[1.02]\"\n",
        "              >\n",
        "                تایید و وارد کردن اطلاعات کالاها\n",
        "              </button>\n",
        "            </div>\n",
        "\n",
        "            <div className=\"flex justify-end pt-4 border-t border-gray-100\">\n",
        "              <button\n",
        "                type=\"submit\"\n",
        "                className=\"px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-black text-xs rounded-xl flex items-center gap-2 cursor-pointer shadow-lg shadow-indigo-600/10\"\n",
        "              >\n",
        "                <Save size={14} />\n",
        "                ذخیره نهایی تنظیمات و برندینگ جدید\n",
        "              </button>\n",
        "            </div>\n",
        "          </form>\n",
        "        </div>\n",
        "      )}\n",
        "\n"
    ]\n",
    new_lines = lines[:start_idx] + content + lines[end_idx:]\n",
    with open(file_path, 'w', encoding='utf-8') as f:\n",
        f.writelines(new_lines)\n",
    print("SUCCESS")\n",
else:\n",
    print("FAILED")
